package beans;
// Generated 3 d�c. 2020 16:11:03 by Hibernate Tools 4.3.1



/**
 * Evenement generated by hbm2java
 */
public class Evenement  implements java.io.Serializable {


     private Integer idevenement;
     private Integer user;
     private String natureevenement;
     private String detailevenement;

    public Evenement() {
    }

    public Evenement(Integer user, String natureevenement, String detailevenement) {
       this.user = user;
       this.natureevenement = natureevenement;
       this.detailevenement = detailevenement;
    }
   
    public Integer getIdevenement() {
        return this.idevenement;
    }
    
    public void setIdevenement(Integer idevenement) {
        this.idevenement = idevenement;
    }
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    public String getNatureevenement() {
        return this.natureevenement;
    }
    
    public void setNatureevenement(String natureevenement) {
        this.natureevenement = natureevenement;
    }
    public String getDetailevenement() {
        return this.detailevenement;
    }
    
    public void setDetailevenement(String detailevenement) {
        this.detailevenement = detailevenement;
    }




}


