package beans;
// Generated 3 d�c. 2020 16:11:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Livraison generated by hbm2java
 */
public class Livraison  implements java.io.Serializable {


     private int idlivraison;
     private Tarification tarification;
     private Integer userByUserIdUserClient;
     private Integer userByUserIduserLivreur;
     private Date datelivraison;
     private String adresserecuperation;
     private Date dateRecuperation;
     private String telephonerrecuperation;
     private String nomCompletDestinataire;
     private String adresselivraison;
     private String naturecolis;
     private String typevehicule;
     private String statutlivraison;
     private String paiement;
     private String statutpaiement;
     private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);

    public Livraison() {
    }

	
    public Livraison(Tarification tarification, Date datelivraison, String adresserecuperation, Date dateRecuperation, String telephonerrecuperation, String nomCompletDestinataire, String adresselivraison, String naturecolis, String typevehicule, String statutlivraison, String paiement) {
        this.tarification = tarification;
        this.datelivraison = datelivraison;
        this.adresserecuperation = adresserecuperation;
        this.dateRecuperation = dateRecuperation;
        this.telephonerrecuperation = telephonerrecuperation;
        this.nomCompletDestinataire = nomCompletDestinataire;
        this.adresselivraison = adresselivraison;
        this.naturecolis = naturecolis;
        this.typevehicule = typevehicule;
        this.statutlivraison = statutlivraison;
        this.paiement = paiement;
    }
    public Livraison(Tarification tarification, Integer userByUserIdUserClient, Integer userByUserIduserLivreur, Date datelivraison, String adresserecuperation, Date dateRecuperation, String telephonerrecuperation, String nomCompletDestinataire, String adresselivraison, String naturecolis, String typevehicule, String statutlivraison, String paiement, String statutpaiement, Set<Reclamation> reclamations) {
       this.tarification = tarification;
       this.userByUserIdUserClient = userByUserIdUserClient;
       this.userByUserIduserLivreur = userByUserIduserLivreur;
       this.datelivraison = datelivraison;
       this.adresserecuperation = adresserecuperation;
       this.dateRecuperation = dateRecuperation;
       this.telephonerrecuperation = telephonerrecuperation;
       this.nomCompletDestinataire = nomCompletDestinataire;
       this.adresselivraison = adresselivraison;
       this.naturecolis = naturecolis;
       this.typevehicule = typevehicule;
       this.statutlivraison = statutlivraison;
       this.paiement = paiement;
       this.statutpaiement = statutpaiement;
     //  this.reclamations = reclamations;
    }
   
    public Integer getIdlivraison() {
        return this.idlivraison;
    }
    
    public void setIdlivraison(Integer idlivraison) {
        this.idlivraison = idlivraison;
    }
    public Tarification getTarification() {
        return this.tarification;
    }
    
    public void setTarification(Tarification tarification) {
        this.tarification = tarification;
    }
    public Integer getUserByUserIdUserClient() {
        return this.userByUserIdUserClient;
    }
    
    public void setUserByUserIdUserClient(Integer userByUserIdUserClient) {
        this.userByUserIdUserClient = userByUserIdUserClient;
    }
    public Integer getUserByUserIduserLivreur() {
        return this.userByUserIduserLivreur;
    }
    
    public void setUserByUserIduserLivreur(Integer userByUserIduserLivreur) {
        this.userByUserIduserLivreur = userByUserIduserLivreur;
    }
    public Date getDatelivraison() {
        return this.datelivraison;
    }
    
    public void setDatelivraison(Date datelivraison) {
        this.datelivraison = datelivraison;
    }
    public String getAdresserecuperation() {
        return this.adresserecuperation;
    }
    
    public void setAdresserecuperation(String adresserecuperation) {
        this.adresserecuperation = adresserecuperation;
    }
    public Date getDateRecuperation() {
        return this.dateRecuperation;
    }
    
    public void setDateRecuperation(Date dateRecuperation) {
        this.dateRecuperation = dateRecuperation;
    }
    public String getTelephonerrecuperation() {
        return this.telephonerrecuperation;
    }
    
    public void setTelephonerrecuperation(String telephonerrecuperation) {
        this.telephonerrecuperation = telephonerrecuperation;
    }
    public String getNomCompletDestinataire() {
        return this.nomCompletDestinataire;
    }
    
    public void setNomCompletDestinataire(String nomCompletDestinataire) {
        this.nomCompletDestinataire = nomCompletDestinataire;
    }
    public String getAdresselivraison() {
        return this.adresselivraison;
    }
    
    public void setAdresselivraison(String adresselivraison) {
        this.adresselivraison = adresselivraison;
    }
    public String getNaturecolis() {
        return this.naturecolis;
    }
    
    public void setNaturecolis(String naturecolis) {
        this.naturecolis = naturecolis;
    }
    public String getTypevehicule() {
        return this.typevehicule;
    }
    
    public void setTypevehicule(String typevehicule) {
        this.typevehicule = typevehicule;
    }
    public String getStatutlivraison() {
        return this.statutlivraison;
    }
    
    public void setStatutlivraison(String statutlivraison) {
        this.statutlivraison = statutlivraison;
    }
    public String getPaiement() {
        return this.paiement;
    }
    
    public void setPaiement(String paiement) {
        this.paiement = paiement;
    }
    public String getStatutpaiement() {
        return this.statutpaiement;
    }
    
    public void setStatutpaiement(String statutpaiement) {
        this.statutpaiement = statutpaiement;
    }
    public Set<Reclamation> getReclamations() {
        return this.reclamations;
    }
    
    public void setReclamations(Set<Reclamation> reclamations) {
        this.reclamations = reclamations;
    }




}


