package beans;
// Generated 3 d�c. 2020 16:11:03 by Hibernate Tools 4.3.1


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 * Profil generated by hbm2java
 */
public class Profil  implements java.io.Serializable {


     private Integer idprofil;
     private String nomProfil;
     private Set<User> users = new HashSet<User>(0);
     private SessionFactory sessionFactory;

    public SessionFactory getSessionFactory() {
        return sessionFactory;
    }

    public void setSessionFactory(SessionFactory sessionFactory) {
        this.sessionFactory = sessionFactory;
    }
     

    public Profil() {
    }

    public Profil(String nomProfil, Set<User> users) {
       this.nomProfil = nomProfil;
       this.users = users;
    }
   
    public Integer getIdprofil() {
        return this.idprofil;
    }
    
    public void setIdprofil(Integer idprofil) {
        this.idprofil = idprofil;
    }
    public String getNomProfil() {
        return this.nomProfil;
    }
    
    public void setNomProfil(String nomProfil) {
        this.nomProfil = nomProfil;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

    
      public List getStudent (){
    List<Profil> profil = null;
    try{
    Session session = sessionFactory.openSession();
    org.hibernate.Transaction tx = session.beginTransaction();
        Query q = session.createQuery("from beans.Profil");
        
        profil = (List<Profil>) q.list();
        
    }catch(Exception e){
    e.printStackTrace();
    }
    return profil;
    }
    
    
    
    private List<String> userrr =  new ArrayList<>();
    public List<String> myuser(){
        Connection connection = null;
         try {
             Class.forName("com.mysql.jdbc.Driver");
       
                        String url = "jdbc:mysql://localhost:3306/livraisonbd" ;
                        Connection conn=DriverManager.getConnection(url, "root", "");
                        PreparedStatement ps = null;
                        ps = conn.prepareStatement("select * from profil");
            		ResultSet rs= ps.executeQuery();
                        
                        while(rs.next()){
                           // userrr.add(rs)
                            userrr.add(rs.getString("login"));
                        }
        
                  } catch (Exception ex) {
            ex.printStackTrace();
                  }
                return userrr;
    }
    



}


