package beans;
// Generated 3 d�c. 2020 16:11:03 by Hibernate Tools 4.3.1



/**
 * Reclamation generated by hbm2java
 */
public class Reclamation  implements java.io.Serializable {


     private Integer idreclamation;
     private Integer livraison;
     private String detailReclamation;

    public Reclamation() {
    }

    public Reclamation(Integer livraison, String detailReclamation) {
       this.livraison = livraison;
       this.detailReclamation = detailReclamation;
    }
   
    public Integer getIdreclamation() {
        return this.idreclamation;
    }
    
    public void setIdreclamation(Integer idreclamation) {
        this.idreclamation = idreclamation;
    }
    public Integer getLivraison() {
        return this.livraison;
    }
    
    public void setLivraison(Integer livraison) {
        this.livraison = livraison;
    }
    public String getDetailReclamation() {
        return this.detailReclamation;
    }
    
    public void setDetailReclamation(String detailReclamation) {
        this.detailReclamation = detailReclamation;
    }




}


