package beans;
// Generated 3 d�c. 2020 16:11:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarification generated by hbm2java
 */
public class Tarification  implements java.io.Serializable {


     private Integer idtarification;
     private String zone;
     private int prix;
     private Set<Livraison> livraisons = new HashSet<Livraison>(0);

    public Tarification() {
    }

	
    
    public Tarification(Integer idtarification,String zone, int prix) {
        this.idtarification = idtarification;
        this.zone = zone;
        this.prix = prix;
    }
    public Tarification(Integer idtarification,String zone, int prix, Set<Livraison> livraisons) {
     this.idtarification = idtarification;
        this.zone = zone;
       this.prix = prix;
       this.livraisons = livraisons;
    }
   
    public Integer getIdtarification() {
        return this.idtarification;
    }
    
    public void setIdtarification(Integer idtarification) {
        this.idtarification = idtarification;
    }
    public String getZone() {
        return this.zone;
    }
    
    public void setZone(String zone) {
        this.zone = zone;
    }
    public int getPrix() {
        return this.prix;
    }
    
    public void setPrix(int prix) {
        this.prix = prix;
    }
    public Set<Livraison> getLivraisons() {
        return this.livraisons;
    }
    
    public void setLivraisons(Set<Livraison> livraisons) {
        this.livraisons = livraisons;
    }




}


