package beans;
// Generated 3 déc. 2020 16:11:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TypeVehicule generated by hbm2java
 */
public class TypeVehicule  implements java.io.Serializable {


     private Integer idtypeVehicule;
     private String nomvehicule;
     private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

    public TypeVehicule() {
    }

	
    public TypeVehicule(String nomvehicule) {
        this.nomvehicule = nomvehicule;
    }
    public TypeVehicule(String nomvehicule, Set<Vehicule> vehicules) {
       this.nomvehicule = nomvehicule;
       this.vehicules = vehicules;
    }
   
    public Integer getIdtypeVehicule() {
        return this.idtypeVehicule;
    }
    
    public void setIdtypeVehicule(Integer idtypeVehicule) {
        this.idtypeVehicule = idtypeVehicule;
    }
    public String getNomvehicule() {
        return this.nomvehicule;
    }
    
    public void setNomvehicule(String nomvehicule) {
        this.nomvehicule = nomvehicule;
    }
    public Set<Vehicule> getVehicules() {
        return this.vehicules;
    }
    
    public void setVehicules(Set<Vehicule> vehicules) {
        this.vehicules = vehicules;
    }




}


