package beans;
// Generated 3 d�c. 2020 16:11:03 by Hibernate Tools 4.3.1


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
//import javax.faces.bean.ManagedBean;
import javax.annotation.ManagedBean;

/**
 * User generated by hbm2java
 */
@ManagedBean
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Profil profil;
     private String nomUser;
     private String prenomUser;
     private String login;
     private String password;
     private Date datenaiss;
     private int telephone;
     private String email;
     private String statutLivreur;
     private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);
     private Set<Destinataire> destinataires = new HashSet<Destinataire>(0);
     private Set<Evenement> evenements = new HashSet<Evenement>(0);
     private Set<Livraison> livraisonsForUserIdUserClient = new HashSet<Livraison>(0);
     private Set<Livraison> livraisonsForUserIduserLivreur = new HashSet<Livraison>(0);

    public User() {
    }

	
    public User(Profil profil, String nomUser, String prenomUser, String login, String password, Date datenaiss, int telephone) {
        this.profil = profil;
        this.nomUser = nomUser;
        this.prenomUser = prenomUser;
        this.login = login;
        this.password = password;
        this.datenaiss = datenaiss;
        this.telephone = telephone;
    }
    public User(Profil profil, String nomUser, String prenomUser, String login, String password, Date datenaiss, int telephone, String email, String statutLivreur, Set<Vehicule> vehicules, Set<Destinataire> destinataires, Set<Evenement> evenements, Set<Livraison> livraisonsForUserIdUserClient, Set<Livraison> livraisonsForUserIduserLivreur) {
       this.profil = profil;
       this.nomUser = nomUser;
       this.prenomUser = prenomUser;
       this.login = login;
       this.password = password;
       this.datenaiss = datenaiss;
       this.telephone = telephone;
       this.email = email;
       this.statutLivreur = statutLivreur;
       this.vehicules = vehicules;
       this.destinataires = destinataires;
       this.evenements = evenements;
       this.livraisonsForUserIdUserClient = livraisonsForUserIdUserClient;
       this.livraisonsForUserIduserLivreur = livraisonsForUserIduserLivreur;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Profil getProfil() {
        return this.profil;
    }
    
    public void setProfil(Profil profil) {
        this.profil = profil;
    }
    public String getNomUser() {
        return this.nomUser;
    }
    
    public void setNomUser(String nomUser) {
        this.nomUser = nomUser;
    }
    public String getPrenomUser() {
        return this.prenomUser;
    }
    
    public void setPrenomUser(String prenomUser) {
        this.prenomUser = prenomUser;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDatenaiss() {
        return this.datenaiss;
    }
    
    public void setDatenaiss(Date datenaiss) {
        this.datenaiss = datenaiss;
    }
    public int getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(int telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatutLivreur() {
        return this.statutLivreur;
    }
    
    public void setStatutLivreur(String statutLivreur) {
        this.statutLivreur = statutLivreur;
    }
    public Set<Vehicule> getVehicules() {
        return this.vehicules;
    }
    
    public void setVehicules(Set<Vehicule> vehicules) {
        this.vehicules = vehicules;
    }
    public Set<Destinataire> getDestinataires() {
        return this.destinataires;
    }
    
    public void setDestinataires(Set<Destinataire> destinataires) {
        this.destinataires = destinataires;
    }
    public Set<Evenement> getEvenements() {
        return this.evenements;
    }
    
    public void setEvenements(Set<Evenement> evenements) {
        this.evenements = evenements;
    }
    public Set<Livraison> getLivraisonsForUserIdUserClient() {
        return this.livraisonsForUserIdUserClient;
    }
    
    public void setLivraisonsForUserIdUserClient(Set<Livraison> livraisonsForUserIdUserClient) {
        this.livraisonsForUserIdUserClient = livraisonsForUserIdUserClient;
    }
    public Set<Livraison> getLivraisonsForUserIduserLivreur() {
        return this.livraisonsForUserIduserLivreur;
    }
    
    public void setLivraisonsForUserIduserLivreur(Set<Livraison> livraisonsForUserIduserLivreur) {
        this.livraisonsForUserIduserLivreur = livraisonsForUserIduserLivreur;
    }

  private List<String> userrr =  new ArrayList<>();
    public List<String> myuser(){
        Connection connection = null;
         try {
             Class.forName("com.mysql.jdbc.Driver");
       
                        String url = "jdbc:mysql://localhost:3306/livraisonbd" ;
                        Connection conn=DriverManager.getConnection(url, "root", "");
                        PreparedStatement ps = null;
                        ps = conn.prepareStatement("select * from user");
            		ResultSet rs= ps.executeQuery();
                        
                        while(rs.next()){
                            userrr.add(rs.getString("login"));
                        }
        
                  } catch (Exception ex) {
            ex.printStackTrace();
                  }
                return userrr;
    }
    
    

  


}


