package beans;
// Generated 3 d�c. 2020 16:11:03 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vehicule generated by hbm2java
 */
public class Vehicule  implements java.io.Serializable {


     private Integer idvehicule;
     private TypeVehicule typeVehicule;
     private Integer user;
     private String marque;
     private String modele;
     private Date dateAchat;
     private Date dateRebus;

    public Vehicule() {
    }

	
    public Vehicule(TypeVehicule typeVehicule, String marque, String modele, Date dateAchat) {
        this.typeVehicule = typeVehicule;
        this.marque = marque;
        this.modele = modele;
        this.dateAchat = dateAchat;
    }
    public Vehicule(TypeVehicule typeVehicule, Integer user, String marque, String modele, Date dateAchat, Date dateRebus) {
       this.typeVehicule = typeVehicule;
       this.user = user;
       this.marque = marque;
       this.modele = modele;
       this.dateAchat = dateAchat;
       this.dateRebus = dateRebus;
    }
   
    public Integer getIdvehicule() {
        return this.idvehicule;
    }
    
    public void setIdvehicule(Integer idvehicule) {
        this.idvehicule = idvehicule;
    }
    public TypeVehicule getTypeVehicule() {
        return this.typeVehicule;
    }
    
    public void setTypeVehicule(TypeVehicule typeVehicule) {
        this.typeVehicule = typeVehicule;
    }
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }
    public String getModele() {
        return this.modele;
    }
    
    public void setModele(String modele) {
        this.modele = modele;
    }
    public Date getDateAchat() {
        return this.dateAchat;
    }
    
    public void setDateAchat(Date dateAchat) {
        this.dateAchat = dateAchat;
    }
    public Date getDateRebus() {
        return this.dateRebus;
    }
    
    public void setDateRebus(Date dateRebus) {
        this.dateRebus = dateRebus;
    }




}


